version: '3.1'

services:
  mysql:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: isucari
      MYSQL_USER: isucari
      MYSQL_PASSWORD: isucari
    ports:
      - 3306:3306
